# Copyright (C) 2025 Daniel Mueller <deso@posteo.net>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build

on:
  workflow_call:
    inputs:
      upload-release:
        description: 'The release to upload artifacts to, if any'
        default: ''
        required: false
        type: string
  workflow_dispatch:

jobs:
  build:
    name: Build statically linked binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install --yes --no-install-recommends musl-tools
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-linux-musl
      - run: |
          CARGO_PROFILE_RELEASE_DEBUG=false CARGO_PROFILE_RELEASE_STRIP=true cargo install --bin=specto --path=. --root=. --target x86_64-unknown-linux-musl
          strip bin/specto
      - uses: actions/upload-artifact@v4
        with:
          name: specto
          path: bin/specto
      - if: ${{ inputs.upload-release != '' }}
        name: Upload release asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mv bin/specto specto
          gh release upload ${{ inputs.upload-release }} specto
